# Generated by Django 3.0.7 on 2020-07-02 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyPage', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hidden_posts',
            field=models.ManyToManyField(blank=True, to='MyPage.Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
