# Generated by Django 3.0.7 on 2020-07-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyPage', '0003_auto_20200702_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='image',
        ),
    ]
