# Generated by Django 3.0.7 on 2020-07-02 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyPage', '0005_auto_20200702_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
