# Generated by Django 3.0.7 on 2020-07-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPage', '0006_auto_20200702_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='image.png', upload_to='images'),
        ),
    ]
