# Generated by Django 3.0.7 on 2020-07-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPage', '0008_auto_20200702_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='No Title', max_length=64),
        ),
    ]
