# Generated by Django 3.0.7 on 2020-07-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPage', '0010_auto_20200703_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default='No Title', max_length=32),
        ),
    ]
