# Generated by Django 3.0.7 on 2020-07-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPage', '0014_auto_20200705_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='No Title', max_length=128),
        ),
    ]
