# Generated by Django 3.0.7 on 2020-07-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPage', '0015_auto_20200705_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='No Title', max_length=64),
        ),
    ]
