# Generated by Django 3.0.7 on 2020-07-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyPage', '0016_auto_20200705_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hidden_posts',
        ),
    ]
